### ISSUE TITLE
great tool!  opendns resolver doesn't work though for me....

### ISSUE THREAD

**Issue by steven-tan** [mthssdrbrg/ddns-route53#1]
So I'm totally unsure why, but the following does not work for me (times out):

dig +short myip.opendns.com @resolver1.opendns.com

It does work fine if I don't specify @resolver1.opendns.com.

For my home purposes I'm just going to leave that part off.

**Comment by mthssdrbrg** [comment]
Huh, that's odd. Does the following work?:
```
dig resolver1.opendns.com
```

You can specify the ip address as a command line argument:
```
ddns-route53 --ip="$(dig +short myip.opendns.com)" <other args>
```
