### ISSUE TITLE
Unable to determine current IP address

### ISSUE THREAD

**Issue by dnissimi** [mthssdrbrg/ddns-route53#3]
Seem like the 'opendns' method for fetching external IP address is broken.

I have a proven the following remedy to be working:
Modify `ddns-route53`, line 73:
    ip="$(curl ifconfig.co)"   ###ip="$(dig +short myip.opendns.com @resolver1.opendns.com)"

Readme.md should be update to require 'curl' as opposed to 'dig'

Thanks for the great work!

**Comment by mthssdrbrg** [comment]
Hm, it works fine for me, what kind of problems are you having? It's also possible to run it like this:

```bash
$ ddns-route53 --zone-id <ZONE_ID> --record-set <RECORD_SET> --ip "$(curl ifconfig.co)"
```

**Comment by dnissimi** [comment]
You are correct.  Seems to be a problem with my 'Luma' router (acting as DNS proxy).  The default 'opendns' method works outside my home.
So I will use the command-line switch as noted above!
Cheers.
